CREATE TABLE HOTEL(
  CODIGO INTEGER, 
  NOMBRE VARCHAR(30) UNIQUE, 
  DIRECCION VARCHAR(90), 
  SITIOWEB VARCHAR(90)
);

CREATE TABLE RESERVACION(
  CODIGO INTEGER, 
  CODIGO_HUESPED INTEGER, 
  CODIGO_HABITACION INTEGER, 
  FECHAINICIO DATE, 
  FECHAFIN DATE
);

CREATE TABLE HABITACION(
  CODIGO INTEGER, 
  CODIGO_HOTEL INTEGER,
  TIPO VARCHAR(30), 
  PRECIO DECIMAL(9, 2) CHECK(PRECIO > 25)
);

CREATE TABLE HUESPED(
  CODIGO INTEGER, 
  NOMBRE VARCHAR(30), 
  EMAIL VARCHAR(90) UNIQUE, 
  TELEFONO VARCHAR(9)
);

ALTER TABLE HUESPED ADD PRIMARY KEY (CODIGO);
ALTER TABLE HOTEL ADD PRIMARY KEY (CODIGO);
ALTER TABLE HABITACION ADD PRIMARY KEY (CODIGO);

INSERT INTO HOTEL
VALUES(1, "Hotel Trivago", "Lomas de San Francisco", "Triv_hotel.com");

INSERT INTO RESERVACION
VALUES(1, 1, 1, "2025-02-22", "2025-02-27");

INSERT INTO HABITACION
VALUES(1, 1, "Suit", "512.00");

INSERT INTO HUESPED
VALUES(1, "Bryan Bustillo", "bryanlexis30@gmail.com", "7453-5756");

SELECT * FROM HOTEL;
SELECT * FROM RESERVACION;
SELECT * FROM HABITACION;
SELECT * FROM HUESPED;