CREATE TABLE ALUMNO(
  ID INTEGER UNIQUE NOT NULL, 
  NOMBRES VARCHAR(20), 
  APELLIDOS VARCHAR(20), 
  DIRECCION VARCHAR(30), 
  CORREO VARCHAR(40), 
  TELEFONO VARCHAR(8),
  FECHA_NACIMIENTO DATE
);

CREATE TABLE MATERIA(
  ID INTEGER UNIQUE NOT NULL, 
  NOMBRE VARCHAR(10), 
  UV CHAR(2), 
  PRERREQUISITOS VARCHAR(10), 
  CICLO CHAR(2)
);

CREATE TABLE TABLA_INSCRIPCION(
  ID_MATERIA INTEGER NOT NULL, 
  ID_ALUMNO INTEGER NOT NULL, 
  MATRICULA VARCHAR(15)
);

ALTER TABLE ALUMNO ADD PRIMARY KEY (ID);
ALTER TABLE MATERIA ADD PRIMARY KEY (ID);

INSERT INTO ALUMNO 
VALUES(1, "Bryan Alexis", "Peña Bustillo", "Mi casa", "bryanlexis30@gmail.com", "74535756", "2006-05-20");

INSERT INTO MATERIA
VALUES(1, "ASB404", "04", "PAL404", "01");

INSERT INTO TABLA_INSCRIPCION
(ID_MATERIA, ID_ALUMNO, MATRICULA)
VALUES(1, 1, "Primera");

SELECT * FROM ALUMNO;
SELECT * FROM MATERIA;
SELECT * FROM TABLA_INSCRIPCION;